version: "3.9"

services:
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
            - "15673:15672"
            - "5673:5672"

    user-auth-controller:
        container_name: user_auth_controller
        build:
            context: ./backend/user_auth_controller/
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - "8000:8000"

    user-temporary-data-service:
        container_name: user_temporary_data_service
        build:
            context: ./backend/user-temporary-data-service/
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - "8001:8001"

    faculties-service:
        container_name: faculties_service
        build:
            context: ./backend/facultiesService/
            dockerfile: Dockerfile
        environment:
            DATABASE_URL: ${DATABASE_URL}
        ports:
            - "8080:8080"

    database:
        container_name: postgres
        image: postgres:16
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: postgres
            POSTGRES_DB: postgres
        ports:
            - "5433:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - "5050:80"

volumes:
    pgdata: {}

networks:
    default: {}
