version: "3"

tasks:
  generate:
    desc: "Generate Go code from proto files"
    cmds:
      - protoc -I proto proto/sso/sso.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative

  clean:
    desc: "Clean generated files"
    cmds:
      - rm -rf gen/go/*

  default:
    desc: "Generate code and clean old generated files"
    deps: [clean, generate]


  migration:
    desc: "Run migrations"
    cmds:
      - goose -dir cmd/db/migrations postgres "user=vremyavnikuda password=vremyavnikuda dbname=vremyavnikuda
      - sslmode=disable" up
